{
	"version": 1737711578,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/angrytaxpayers-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite8-sheet1.png",
		"images/sprite8-sheet2.png",
		"images/tiledbackground2.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"images/sprite16-sheet2.png",
		"images/sprite16-sheet3.png",
		"images/sprite16-sheet4.png",
		"images/sprite16-sheet5.png",
		"images/particles.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"media/explosion-under-snow-sfx-230505.m4a",
		"media/explosion-under-snow-sfx-230505.ogg",
		"media/cassh machine.m4a",
		"media/cassh machine.ogg",
		"media/rednecks.m4a",
		"media/rednecks.ogg",
		"media/tank.m4a",
		"media/tank.ogg",
		"media/trump 1.m4a",
		"media/trump 1.ogg",
		"media/trump 2.m4a",
		"media/trump 2.ogg",
		"media/trump 3.m4a",
		"media/trump 3.ogg",
		"media/trump 4.m4a",
		"media/trump 4.ogg",
		"media/biden.m4a",
		"media/biden.ogg",
		"media/woke.m4a",
		"media/woke.ogg",
		"media/rednecks 2.m4a",
		"media/rednecks 2.ogg",
		"media/mgwtf - american gdp - bgm.m4a",
		"media/mgwtf - american gdp - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}